name: Check Pod status

on: workflow_dispatch

jobs:
  check-pods:
    runs-on: ubuntu-latest
    steps:
- name: Connect to Kubernetes Host
      run: |
        set -x
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{ secrets.SSH_PKEY }}" 
        ssh-keyscan -p 32510 ${{ secrets.BASTION_IP_JUMP }} >> ~/.ssh/known_hosts
        ssh ${{ secrets.BASTION_USER_JUMP }}@${{ secrets.BASTION_IP_JUMP }} -p 32510 ssh-keyscan ${{ secrets.VHOST_IP }} >> ~/.ssh/known_hosts
        ssh -o ProxyCommand="ssh -W %h:%p ${{ secrets.BASTION_USER_JUMP }}@${{ secrets.BASTION_IP_JUMP }} -p 32510" ${{ secrets.VHOST_USER }}@${{ secrets.VHOST_IP }} "kubectl get pods -A" >> output-pods.log

    - name: Check Crash pods
      id: check-pods
      run: |
        echo "steps.p_c.outputs.output_log" > output.log
        echo "pods-failed=$(cat output.log | grep -v 'Running\|Completed ' | wc -l)" >> $GITHUB_OUTPUT
    - name: Upload Crashed Pods List
      if: steps.check-pods.outputs.pods-failed == 1
      uses: actions/upload-artifact@v3
      with:
        path: output.log

    - name: Slack notification
      uses: rtCamp/action-slack-notify@v2
      if: steps.check-pods.outputs.pods-failed == 1
      env:
        SLACK_CHANNEL: 'general'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_COLOR: ${{ job.status }}
        SLACK_USERNAME: rtBot
        SLACK_TITLE: "Failed Pods Alert"
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}